version: 2
updates:
  - package-ecosystem: yarn
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
      timezone: Europe/Londo
    open-pull-requests-limit: 10
    reviewers:
      - EpicKris
    labels:
      - dependencies
    versioning-strategy: increase
    rebase-strategy: disabled
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
      timezone: Europe/London
